apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-env
  labels:
    io.iot.service: iot-env
data:
  ENVIRONMENT: DEV
  GIN_PORT: '8080'
  POSTGRES_HOST: postgres
  POSTGRES_PORT: '5432'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iot-env-pg-cluster
  labels:
    io.iot.service: iot-env-pg-cluster
data:
  ENVIRONMENT: DEV
  GIN_PORT: '8080'
  POSTGRES_HOST: pg-cluster
  POSTGRES_PORT: '5432'

---
apiVersion: v1
kind: Secret
metadata:
  name: iot-pg-cluster-secret
  labels:
    io.iot.service: iot-db-secret
type: Opaque
data:
  POSTGRES_USER: cG9vbGVy  # Base64 encoded value for 'pooler'
  POSTGRES_PASSWORD: WVBFcUNJYjlPOGZDV2RzQ2xsaDd2MXpScDFEUGFDaW85Rm5BRk1VbGVIVjh5MnR2bmh6SlBDYjh6ZUZTVnpDMw==
  POSTGRES_DATABASE: aW90  # Base64 encoded value for 'iot'