{
 "title": "Postgres Exporter",
 "tags": [ "postgres" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(pg_up{job=\"postgres-exporter\"}, instance)"
   },
   {
    "name": "db",
    "label": "Database",
    "query": "label_values(pg_stat_database_tup_fetched_total{instance=~\"$instance\", datname!~\"postgres|template.*\"}, datname)"
   }
  ]
 },
 "panels": [
  {
   "title": "Rows Operations",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_tup_fetched_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Fetched"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_returned_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Returned"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_inserted_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Inserted"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_updated_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Updated"
    },
    {
     "expr": "sum(rate(pg_stat_database_tup_deleted_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Deleted"
    }
   ]
  },
  {
   "title": "Queries Per Second (QPS)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit_total{datname=~\"$db\",instance=~\"$instance\"}[5m])) + sum(rate(pg_stat_database_xact_rollback_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "Buffers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "irate(pg_stat_bgwriter_buffers_alloc_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Buffers Allocated"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_fsync_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Buffers Backend FSYNC"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_backend_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Buffers Backend"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_clean_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Buffers Clean"
    },
    {
     "expr": "irate(pg_stat_bgwriter_buffers_checkpoint_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "Buffers Checkpoint"
    }
   ]
  },
  {
   "title": "Conflicts & Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_deadlocks_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Deadlocks"
    },
    {
     "expr": "sum(rate(pg_stat_database_conflicts_total{datname=~\"$db\",instance=~\"$instance\"}[5m]))",
     "legendFormat": "Conflicts"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(pg_stat_database_blks_hit{datname=~\"$db\",instance=~\"$instance\"}) / (sum(pg_stat_database_blks_hit{datname=~\"$db\",instance=~\"$instance\"}) + sum(pg_stat_database_blks_read{datname=~\"$db\",instance=~\"$instance\"}))",
     "legendFormat": "Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Number of Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pg_stat_database_numbackends_total{datname=~\"$db\",instance=~\"$instance\"}",
     "legendFormat": "Active Connections"
    }
   ]
  }
 ]
}