apiVersion: acid.zalan.do/v1
kind: postgresql

metadata:
  labels:
    team: acid
  name: pg-cluster
  namespace: usp-dev
  annotations:
    # Configure the connection pooler parameters
    connection-pooler-configuration: |
      max_client_conn = 400
      default_pool_size = 20
spec:
  allowedSourceRanges: null
  databases:
    iot: usp
  enableConnectionPooler: true
  enableMasterLoadBalancer: false
  enableMasterPoolerLoadBalancer: false
  numberOfInstances: 6
  connectionPooler:
    numberOfInstances: 4
    mode: transaction
    # parameters:
    #   default_pool_size: 20
    #   max_client_conn: 400
    schema: pooler
    user: pooler
    resources:
      requests:
        cpu: 500m
        memory: 1500Mi
      limits:
        cpu: 1500m
        memory: 6500Mi
  postgresql:
    version: '17'
    parameters:
      shared_buffers: '32MB'
      max_connections: '1000'
      superuser_reserved_connections: '50'
  patroni:
    initdb:
      encoding: UTF8
      data-checksums: "true"
    ttl: 30
    loop_wait: 10
    retry_timeout: 10
    maximum_lag_on_failover: 1048576
  resources:
    limits:
      cpu: 1000m
      memory: 6000Mi
    requests:
      cpu: 500m
      memory: 1500Mi
  teamId: acid
  users:
    usp:
      - superuser
      - createdb
    pooler:
      - login
      - superuser

  volume:
    size: 20Gi
    storageClass: microk8s-hostpath
  preparedDatabases:
    iot:
      defaultUsers: true
      extensions:
        pg_stat_statements: ""
      schemas:
        public: {}